HARDCODED_HOST = "127.0.0.1"
HARDCODED_PORT = 6000
HARDCODED_BUFFER_SIZE = 1024
HARDCODED_TIMEOUT = 4
HARDCODED_CHUNK_SIZE = 200
UPLOAD_FINISH_MSG = "FINARDO"
HARDCODED_MOUNT_PATH = "./server_files/"
